accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('update_profile/', views.UserUpdateProfileView.as_view(), name='update_profile'),
    path('change_password/', views.UserChangePasswordView.as_view(), name='change_password'),
    path('reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('otplogin/', views.UserOtpLoginView.as_view(), name='user_otplogin'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('loginverify/', views.UserLoginVerifyCodeView.as_view(), name='login_verify_code'),
    path('upload_profile/', views.UploadProfileImageView.as_view(), name='upload_profile'),
    path('change_sms_form/', views.ChangeSmsFormView.as_view(), name='change_sms_form'),
    path('api_register/', views.ApiRegisterView.as_view(), name='api_register'),
    path('api_login/', views.ApiLoginView.as_view(), name='api_login'),
    path('api_logout/', views.ApiLogoutView.as_view(), name='api_logout'),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj/<str:key>', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
    path('upload/', views.UploadImageView.as_view(), name='upload'),
    
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('bucket_pics/',views.BucketPicsView.as_view(), name='bucket_pics'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('favorite/<slug:slug>/', views.FavoriteView.as_view(), name='product_fav'),
    path('favorites_list/', views.MyFavoritesListView.as_view(), name='my_fav_pr'),
    path('api/', views.ApiView.as_view(), name='api'),
    path('api_request/', views.PersonApiRequestView.as_view(), name='api_req'),
    path('api_request_user/', views.UserApiRequestView.as_view(), name='api_req_user'),
    path('api_question/', views.QuestionApiRequestView.as_view(), name='api_question'),    
    path('api_question/create/', views.QuestionApiCreateView.as_view(), name='api_q_create'),
    path('api_question/Update/<int:pk>/', views.QuestionApiUpdateView.as_view(), name='api_q_update'),
    path('api_question/Delete/<int:pk>/', views.QuestionApiDeleteView.as_view(), name='api_q_delete'),
    path('ai_page/', views.AiPageView.as_view(), name='ai_page'),
    
]
# bucket should be higher than product_detail and delete
# path('upload_obj/', views.UploadBucketObject.as_view(), name='upload_obj_bucket'),

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('unpaid/', views.UnpaidOrderView.as_view(), name='unpaid_orders'),
    path('paid/', views.paidOrderView.as_view(), name='paid_orders'),
    path('unpaid_detail/<int:order_id>/', views.UnpaidDetailView.as_view(), name='unpaid_detail'),
    path('paid_detail/<int:order_id>/', views.PaidDetailView.as_view(), name='paid_detail'),
    path('delete_unpaid/<int:order_id>/', views.DeleteUnpaidOrderView.as_view(), name='delete_unpaid'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# dont forget to delete "+ static(settings..." in production mode

home/forms.py
from django import forms
from .models import Comment


class ImageUploadForm(forms.Form):
    name = forms.CharField(max_length=200)
    image = forms.ImageField()

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'text']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class SearchForm(forms.Form):
    search = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'placeholder':'Enter keywords to search products: white cat'}))

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class ApiQuestionForm(forms.Form):
    #user = forms.IntegerField(label='User id')
    #username = forms.CharField(max_length=200, disabled=True, required=False)
    title = forms.CharField(max_length=200)
    body = forms.CharField(max_length=2000)

    def __init__(self, *args, **kwargs):
        super(ApiQuestionForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Product, Category, Comment, Favorite
from . import tasks
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ImageUploadForm, CommentForm, SearchForm, ApiQuestionForm
from bucket import bucket, list_s3_images
import os, requests
from utils import IsAdminUserMixin, get_api_headers
from shop import settings
from orders.forms import CartAddForm
from django.db.models import Q
from django.views.generic import TemplateView, RedirectView


class HomeView(View):
    form_class = SearchForm
    """we have different urls that links to this view, some wont send 
    category_slug and it ends with an error, unless we use category_slug=None"""
    def get(self, request, category_slug=None):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub=False)
        #sub_categories = Category.objects.filter(is_sub=True)
        form = self.form_class
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        search_query = request.GET.get('search')
        if search_query:
            products = products.filter(
                Q(description__icontains=search_query) |
                Q(name__icontains=search_query))
        return render(request, 'home/home.html', {'products':products, 'categories':categories, 'form':form})
    

class ProductDetailView(View):
    def get(self, request, slug):
        product = Product.objects.get(slug=slug)
        comments = Comment.objects.filter(product=product)
        if request.user.is_authenticated:
            is_fav = Favorite.objects.filter(user=request.user, product=product).exists()
        else:
            is_fav = False
        return render(request, 'home/detail.html', {
            'product':product, 'form1':CartAddForm, 'form2':CommentForm, 'comments':comments, 'is_fav':is_fav})
    
    def post(self, request, slug):
        form2 = CommentForm(request.POST)
        if form2.is_valid():
            cd = form2.cleaned_data
            comment = Comment.objects.create(user=request.user, product=Product.objects.get(slug=slug), title=cd['title'], text=cd['text'])
            comment.save()
            return redirect('home:home')
    

class BucketHome(IsAdminUserMixin, View):
    template_name = 'home/bucket.html'
    def get(self, request):
        objects = tasks.all_bucket_objects_task()
        # all_bucket_objects_task.delay() if async.
        objects = sorted(objects, key=lambda x: x['LastModified'], reverse=True) # order by LastModified
        return render(request, self.template_name, {'objects':objects})
    
class DeleteBucketObject(IsAdminUserMixin, View):
    def get(self, request, key):
        if settings.CELERY_IS_ACTIVE:
            tasks.delete_object_task.delay(key)
            messages.success(request, 'your object will be deleted soon...', 'info')
        else:
            bucket.delete_object(key)
            print("settings.CELERY_IS_ACTIVE is False")
            messages.success(request, 'your object is deleted', 'success')
        next_url = request.GET.get('next') # super useful, by adding ?next={{ request.path }} at the end of url tag in html file!
        return redirect(next_url)
        #return redirect('home:bucket')


class DownloadBucketObject(IsAdminUserMixin, View):
    def get(self, request, key):
        if settings.CELERY_IS_ACTIVE:
            tasks.download_object_task.delay(key)
            messages.success(request, 'your object will be downloaded soon...', 'info')
        else:
            bucket.download_object(key)
            print("settings.CELERY_IS_ACTIVE is False")
            messages.success(request, 'your object is downloaded', 'success')
        return redirect('home:bucket')


class UploadImageView(IsAdminUserMixin, View):
    form_class = ImageUploadForm
    template_name = "home/upload.html"
    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            image_file = request.FILES['image']
            name_from_form = form.cleaned_data['name']

            original_ext = os.path.splitext(image_file.name)[1] # .jpg or .png
            final_file_name = name_from_form + original_ext

            file_content = image_file.read()
            if settings.CELERY_IS_ACTIVE:
                tasks.upload_object_task.delay(final_file_name, file_content)
                messages.success(request, 'Your object is uploaded with custom name', 'info')
            else:
                bucket.upload_object(final_file_name, file_content)
                print("settings.CELERY_IS_ACTIVE is False")
                messages.success(request, 'Your object is uploaded', 'success')
            
            return redirect('home:bucket')

        messages.error(request, 'Something went wrong! Please try again', 'danger')
        return render(request, self.template_name, {'form': form})
    
class BucketPicsView(IsAdminUserMixin, View):
    template_name = 'home/bucketpics.html'
    def get(self, request):
        pics = list_s3_images()[1]
        return render(request, self.template_name, {'pics':pics})

class FavoriteView(LoginRequiredMixin, View):
    def get(self, request, slug):
        product = Product.objects.get(slug=slug)
        comments = Comment.objects.filter(product=product)
        user = request.user
        product = Product.objects.get(slug=slug)
        context = {'product':product, 'form1':CartAddForm, 'form2':CommentForm, 'comments':comments}
        already_fav = Favorite.objects.filter(user=user, product=product).first()
        print(already_fav)
        if already_fav is None:
            favorite = Favorite.objects.create(user=user, product=product)
            favorite.save()
            context['is_fav'] = True
            print(context['is_fav'])
            messages.success(request, f'the product "{product.name}" has been added to your favorite list.', 'success')
            return redirect('home:product_detail', slug=slug)
        context['is_fav'] = False
        print(context['is_fav'])
        already_fav.delete()
        messages.error(request, f'the product "{product.name}" has been removed from your favorite list.', 'warning')
        return redirect('home:product_detail', slug=slug)
    
class MyFavoritesListView(LoginRequiredMixin, View):
    def get(self, request):
        favorites = Favorite.objects.filter(user=request.user)
        products =[]
        for fav in favorites:
            products.append(fav.product)
        return render(request, 'home/my_favorite.html', {'products':products})
    
class ApiView(LoginRequiredMixin, TemplateView):
    template_name = 'home/api.html'
    """def get(self, request):
        return render(request, 'home/api.html')"""
    

class PersonApiRequestView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            url = 'http://127.0.0.1:8000/'
            headers = get_api_headers(request)
            json_response = requests.get(url, headers=headers).json()
            try:
                er = json_response['detail']
                messages.error(request, f'api response: {er}', 'warning')
            except:
                messages.success(request, f'data recieved successfully', 'success')
            return render(request, 'home/api_result.html', {'json_response':json_response})
        except:
            messages.error(request, 'API connection failed.', 'warning')
            return redirect('home:api')
        
class UserApiRequestView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            url = 'http://127.0.0.1:8000/accounts/user'
            headers = get_api_headers(request)
            json_response = requests.get(url, headers=headers).json()
            try:
                er = json_response['detail']
                messages.error(request, f'api response: {er}', 'warning')
            except:
                messages.success(request, f'data recieved successfully', 'success')
            return render(request, 'home/api_user_result.html', {'json_response':json_response})
        except:
            messages.error(request, f'API connection failed.', 'warning')
            return redirect('home:api')
        
class QuestionApiRequestView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            url = 'http://127.0.0.1:8000/questions/'
            headers = get_api_headers(request)
            json_response = requests.get(url, headers=headers).json()
            request.session['questions'] = json_response # using sessions for update
            try:
                er = json_response['detail']
                messages.error(request, f'api response: {er}', 'warning')
            except:
                messages.success(request, f'data recieved successfully', 'success')
            return render(request, 'home/api_q_get.html', {'json_response':json_response})
        except:
            messages.error(request, 'API connection failed', 'warning')
            return redirect('home:api')

class QuestionApiCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = ApiQuestionForm()
        #form.user, form.username = request.session['api_id'], request.session['api_username']
        return render(request, 'home/api_q_create.html', {'form':form})

    def post(self, request):
        form = ApiQuestionForm(request.POST)
        if form.is_valid():
            try:
                url = 'http://127.0.0.1:8000/question/create/'
                headers = get_api_headers(request)

home/templates/home/api.html
{% extends 'base.html' %}

{% block content %}
    <h2>API Links</h2>
    <br><hr>
    {% if request.session.api_username %}
    <br>
    <a href="{% url 'accounts:api_logout' %}" class="btn btn-danger">API Logout</a>
    {% else %}
    <a href="{% url 'accounts:api_login' %}" class="btn btn-primary">API Login</a>
    <br>
    <br>
    <a href="{% url 'accounts:api_register' %}" class="btn btn-success">API Register</a>
    {% endif %}
    <br>
    <br>
    <a href="{% url 'home:api_req' %}" class="btn btn-info">send API request for persons</a>
    <br>
    <br>
    <a href="{% url 'home:api_req_user' %}" class="btn btn-info">send API request for users</a>
    <br>
    <br>
    <a href="{% url 'home:api_question' %}" class="btn btn-info">API Questions</a>
    <br>
    <br>
    
{% endblock %}

home/templates/home/api_q_create.html
{% extends 'base.html' %}

{% block content %}
    
    <h2>API questions Create Form</h2><br>
    <br>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create">
        </form>
        
{% endblock %}

home/templates/home/api_q_get.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'home:api_q_create' %}" class="btn btn-danger">Create question</a>
    <br><hr/>
    <h2>API questions list</h2><br>
    <br>
        <ul>
            {% for j in json_response %}
                <li><b>Question {{ j.id }}:</b> {{ j.username }} asked "{{ j.body }}"  -  {{ j.created }}
                </li>
                <b>answers :</b><br>
                {% for i in j.answers %}
                {{ i.username2 }} answered: "{{ i.body}}"<br>
                {% empty %}
                no answer<br>
                {% endfor %}
                {% if request.session.api_username == j.username %} 
                <a href="{% url 'home:api_q_update' j.id %}" class="btn btn-warning">Update question</a>
                <a href="{% url 'home:api_q_delete' j.id %}" class="btn btn-danger">Delete question</a>
                {% endif %}
                <br><br>
            {% endfor %}
        </ul><br><br>
        
{% endblock %}

home/templates/home/api_q_update.html
{% extends 'base.html' %}

{% block content %}
    
    <h2>API questions Update Form</h2><br>
    <form>
        <div class="mb-6">
            <label for="exampleInputEmail1" class="form-label">User ID</label>
            <input type="email" class="form-control" value="{{question_data.user}}" readonly data-bs-toggle="tooltip"
                title="You can not change this field">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Username</label>
            <input class="disabled form-control" value="{{question_data.username}}" readonly data-bs-toggle="tooltip"
                title="You can not change this field">
        </div>
    </form>
   
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
    <br>
{% endblock %}

home/templates/home/api_result.html
{% extends 'base.html' %}

{% block content %}
    <h2>API results</h2><br>
        <ul>
            {% for j in json_response %}
                <li>{{ j.name }} - {{ j.age }} - {{ j.email }}</li>
            {% endfor %}
        </ul><br><br>
{% endblock %}

home/templates/home/api_user_result.html
{% extends 'base.html' %}

{% block content %}
    <h2>API results</h2><br>
        <ul>
            {% for j in json_response %}
                <li>id : {{ j.id }} - username : {{ j.username }} - email : {% if j.email %}{{j.email}}{% else %}no email{% endif %}</li>
            {% endfor %}
        </ul><br><br>
{% endblock %}

home/templates/home/bucket.html
{% extends 'base.html' %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'home:upload' %}">Upload</a>            <a class="btn btn-info" href="{% url 'home:bucket_pics' %}">All Bucket Pictures</a>
    <br\>
    <hr>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Last Modified</th>
      <th scope="col">Size</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for obj in objects %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ obj.Key }}</td>
      <td>{{ obj.LastModified|timesince }} ago</td>
      <td>{{ obj.Size|filesizeformat }}</td>
      <td><a href="{% url 'home:download_obj_bucket' obj.Key %}" class="btn btn-primary">Download</a>
      <a href="{% url 'home:delete_obj_bucket' obj.Key %}?next={{ request.path }}" class="btn btn-danger">Delete</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

home/templates/home/bucketpics.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for pic in pics %}
                <div class="col-md-3 mb-4">
                    <div class="card">
                    <img src="{{ pic.url }}" class="card-img-top" alt="{{ pic.key }}">
                    <div class="card-body">
                        <p class="card-text">{{ pic.key }}</p>
                        <a href="{{ pic.url }}" class="btn btn-sm btn-primary" download>download</a>
                        <a href="{% url 'home:delete_obj_bucket' pic.key %}?next={{ request.path }}" class="btn btn-sm btn-danger">delete</a>
                        <a href="#" class="btn btn-sm btn-secondary">{{pic.size|filesizeformat }}</a>
                    </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="card mb-3 ms-4">
    <img src="{{ product.image_url }}" class="card-img-top" alt="{{ product.name }}" style="max-width: 1200px;">
    <div class="card-body">
        <h4 class="card-title">{{ product.name }}</h4>
        <p class="card-text">description: {{ product.description|safe }}</p>
        <a href="{% url 'home:product_fav' product.slug %}" class="btn btn-danger {% if not request.user.is_authenticated %} disabled {% endif %}">
            {% if not request.user.is_authenticated %}please login, so you can add this product to your favorites{% elif is_fav %}remove from my favorites{% else %}add to my favorites{% endif %}</a>
        <br><br>
        <b>price: {{ product.price }} $</b>
        <p class="card-text"><small class="text-body-secondary">{{ product.created }}</small></p><br>

    <form action="{% url 'orders:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{form1.as_p}}
        <input type="submit" value="Add to Cart" class="btn btn-primary">
    </form>
    </div>
    <br/><hr>
    <h4 class="card-title">Comments</h4>
    <br/>
    {% for comment in comments %}
    <div class="card">
        <div class="card-header">
            {{ comment.title }}
        </div>
        <div class="card-body">
            <figure>
            <blockquote class="blockquote">
                <p>{{ comment.text }}</p>
            </blockquote>
            <figcaption class="blockquote-footer">
                {{ comment.user.full_name }} - {{ comment.updated|timesince }} ago 
            </figcaption>
            </figure>
        </div>
    </div>
    <br/>
    {% endfor %}

    <br/><br/>
    <form action="" method="post">
        {% csrf_token %}
        {{form2.as_p}}
        <input type="submit" value="send comment" class="btn btn-info">
    </form>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra_headers %} 
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{%endblock%}

{% block content %}
    {% for category in categories %}
        <div class="btn-group">
            <a href="{{ category.get_absolute_url }}" class="btn btn-info">{{ category.name }}</a>
            <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                {% for sub in category.scategory.all %}
                <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    <br><br>
    <form action="" method="get">
        {{form.as_p}}
        <input type="submit" value="Search Product" class="btn btn-dark">
    </form>
    <br>
    <a href="{% url 'home:ai_page' %}" class="btn btn-info">AI Page</a>
    <br>
    <br/><hr>
        <div class="container">
            <div class="row">
                {% for product in products %}
                <div class="col-md-4 mb-5">
                    <div class="card">
                        <img src="{{ product.image_url }}" alt="{{ product.name }}"  class="card-img-top" >
                        <div class="card-body">
                        <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

home/templates/home/my_favorite.html
{% extends 'base.html' %}

{% block content %}
    <h2>My Favorite Products</h2><br>
    <b>
        <div class="container">
                <div class="row">
                    {% for product in products %}
                    <div class="col-md-3 mb-5">
                        <div class="card">
                            <img src="{{ product.image_url }}" alt="{{ product.name }}"  class="card-img-top">
                            <div class="card-body">
                            <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }} - price: {{product.price}} $</a>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                        <p>you dont have any favorite product yet!</p>
                    {% endfor %}
                </div>
            </div>
    
    </b><br><br>
{% endblock %}

home/templates/home/upload.html
{% extends 'base.html' %}

{% block content %}
    
<h4>Upload Media</h4>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Upload">
    </form>
{% endblock %}