home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj/<str:key>', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
    path('upload/', views.UploadImageView.as_view(), name='upload'),
    
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('bucket_pics/',views.BucketPicsView.as_view(), name='bucket_pics'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('favorite/<slug:slug>/', views.FavoriteView.as_view(), name='product_fav'),
    path('favorites_list/', views.MyFavoritesListView.as_view(), name='my_fav_pr'),
    path('api/', views.ApiView.as_view(), name='api'),
    path('api_request/', views.PersonApiRequestView.as_view(), name='api_req'),
    path('api_request_user/', views.UserApiRequestView.as_view(), name='api_req_user'),
    path('api_question/', views.QuestionApiRequestView.as_view(), name='api_question'),    
    path('api_question/create/', views.QuestionApiCreateView.as_view(), name='api_q_create'),
    path('api_question/Update/<int:pk>/', views.QuestionApiUpdateView.as_view(), name='api_q_update'),
    path('api_question/Delete/<int:pk>/', views.QuestionApiDeleteView.as_view(), name='api_q_delete'),
    path('ai_page/', views.AiPageView.as_view(), name='ai_page'),
    
]
# bucket should be higher than product_detail and delete
# path('upload_obj/', views.UploadBucketObject.as_view(), name='upload_obj_bucket'),

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('unpaid/', views.UnpaidOrderView.as_view(), name='unpaid_orders'),
    path('paid/', views.paidOrderView.as_view(), name='paid_orders'),
    path('unpaid_detail/<int:order_id>/', views.UnpaidDetailView.as_view(), name='unpaid_detail'),
    path('paid_detail/<int:order_id>/', views.PaidDetailView.as_view(), name='paid_detail'),
    path('delete_unpaid/<int:order_id>/', views.DeleteUnpaidOrderView.as_view(), name='delete_unpaid'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# dont forget to delete "+ static(settings..." in production mode

orders/models.py
from django.db import models
from home.models import Product
from accounts.models import User # or from django.conf import settings (settings.AUTH_USER_MODEL)
# or from django.contrib.auth import get_user_model ( user = models.ForeignKey(get_user_model()) )
from django.core.validators import MinValueValidator, MaxValueValidator

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.IntegerField(blank=True, null=True, default=0)

    class Meta:
        ordering = ['paid', '-updated']

    def __str__(self):
        return f'{self.user} - {str(self.id)}'

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            return int(total*(1-self.discount/100))
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity
    
class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(90)])
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.code

orders/forms.py
from django import forms
from .models import Coupon

class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9, initial=1)

"""class CouponForm(forms.ModelForm):
    class Meta:
        Model = Coupon
        fields = ['code']"""

class CouponForm(forms.Form):
    code = forms.CharField()

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .cart import Cart
from home.models import Product
from .forms import CartAddForm, CouponForm
from .models import Order, OrderItem, Coupon
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.conf import settings
import requests, json
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from datetime import datetime


class CartView(View):
    def get(self, request, order_id=None):
        cart = Cart(request) # we should use __iter__ method in cart.py so we can send an iterable value to cart.html
        return render(request, 'orders/cart.html', {'cart':cart})
    
class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product=product, quantity=form.cleaned_data['quantity'])
        return redirect('orders:cart')
    
class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')
    
class OrderDetailView(LoginRequiredMixin, View):
    template_name = 'orders/order.html'
    form_class = CouponForm
    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id, paid=False)
        return render(request, self.template_name, {'order':order, 'form':self.form_class})
    
    def post(self, request, order_id):
        form = self.form_class(request.POST)
        now = datetime.now()
        order = get_object_or_404(Order, id=order_id)
        if form.is_valid():
            coupon = Coupon.objects.filter(code__exact=form.cleaned_data['code'], valid_from__lte=now, valid_to__gte=now, active=True).first()
            if coupon:
                order.discount = coupon.discount
                messages.success(request, 'coupon has been activated','success')
                return render(request, self.template_name, {'order':order})
            else:
                messages.error(request, 'this coupon is not valid','danger')
                return render(request, self.template_name, {'order':order, 'form':form})
        return render(request, self.template_name, {'order':order, 'form':form})
            
                
    
class OrderCreateView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user = request.user)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
            # cart.remove(item['product']) or :
        cart.clear()
        return redirect('orders:order_detail', order.id)

#? sandbox merchant 
if settings.SANDBOX:
    sandbox = 'sandbox'
else:
    sandbox = 'www'
ZP_API_REQUEST = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = f"https://{sandbox}.zarinpal.com/pg/StartPay/"
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
CallbackURL = 'http://127.0.0.1:8080/orders/verify/'


class OrderPayView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = Order.objects.get(id=order_id)
        request.session['order_pay'] = {'order_id':order.id}
        data = {
            "MerchantID": settings.MERCHANT,
            "Amount": order.get_total_price(),
            "Description": description,
            "Phone": request.user.phone_number,
            "CallbackURL": CallbackURL,
        }
        data = json.dumps(data)
        headers = {
            'content-type': 'application/json',
            'content-length': str(len(data))
        }
        # in Production mode, dont use HttpResponse, create a nice clean html page for it  
        # and show messages with from django.contrib import messages
        try:
            response = requests.post(ZP_API_REQUEST, data=data, headers=headers, timeout=10)

            if response.status_code == 200:
                response_data = response.json()
                if response_data['Status'] == 100:
                    pay_url = ZP_API_STARTPAY + str(response_data['Authority'])
                    return HttpResponseRedirect(pay_url)
                else:
                    return JsonResponse(f"خطای زرین‌پال: {response_data['Status']}")
            else:
                return HttpResponse("خطا در برقراری ارتباط با زرین‌پال")

        except requests.exceptions.Timeout:
            return HttpResponse("خطا: ارتباط با زرین‌پال زمان‌بر شد")
        except requests.exceptions.ConnectionError:
            return HttpResponse("خطا: اتصال به زرین‌پال برقرار نشد")
    
class OrderVerifyView(LoginRequiredMixin, View):
    def get(self, request):
        order_id = request.session['order_pay']['order_id']
        order = Order.objects.get(id=order_id)
        # old method: should be checked after having legit Pay portal
        t_status = request.GET.get('Status')
        t_authority = request.GET.get('Authority')
        if t_status == 'OK':
            req_headers = {'accept': 'application/json', 'content-type': 'application/json' }
            req_data = {
            "MerchantID": settings.MERCHANT,
            "Amount": order.get_total_price(),
            "Authority": t_authority,
            }
            req = request.post(url=ZP_API_VERIFY, data=json.dump(req_data), headers=req_headers)
            if len(req,json()['errors']) == 0:
                t_status = req.json()['data']['code']
                if t_status == 100:
                    return HttpResponse('Transaction success.\nRefID: ' + str(req.json()['data']['ref_id']))
                    order.paid = True # important to verify the successfull transaction for our website!
                    order.save()
                    # also, we should create a model and save all reference ids (RefID) 
                elif t_status == 101:
                    return HttpResponse('Transaction submitted : ' + str(req.json()['data']['message']))
                else:
                    return HttpResponse('Transaction failed.\nStatus: ' + str(req.json()['data']['message']))
            else:
                e_code = req.json()['errors']['code']
                e_message = req.json()['data']['message']
                return HttpResponse(f'Error code: {e_code}, Error message: {e_message}')
        else:
            return HttpResponse('Transaction failed or canceled by user')
        
        # new method: should be checked after having legit Pay portal
        """data = {
            "MerchantID": settings.MERCHANT,
            "Amount": amount,
            "Authority": authority,
        }
        data = json.dumps(data)
        # set content length by data
        headers = {'content-type': 'application/json', 'content-length': str(len(data)) }
        response = requests.post(ZP_API_VERIFY, data=data,headers=headers)

        if response.status_code == 200:
            response = response.json()
            if response['Status'] == 100:
                return {'status': True, 'RefID': response['RefID']}
                order.paid = True # important to verify the successfull transaction for our website!
                order.save()
            else:
                return {'status': False, 'code': str(response['Status'])}
        return response"""

class UnpaidOrderView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        orders = Order.objects.filter(user=user, paid=False)
        return render(request,'orders/unpaid_orders.html', {'orders':orders})
    
class DeleteUnpaidOrderView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        Order.objects.filter(id=order_id, paid=False).delete()
        return redirect('orders:unpaid_orders')

class UnpaidDetailView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = Order.objects.get(id=order_id, paid=False)
        orderitems = order.items.all()
        return render(request, 'orders/unpaid_detail.html', {'order':order, 'orderitems':orderitems})
    
class paidOrderView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        orders = Order.objects.filter(user=user, paid=True)
        return render(request, 'orders/paid_orders.html', {'orders':orders})
    
class PaidDetailView(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = Order.objects.get(id=order_id, paid=True)
        orderitems = order.items.all()
        return render(request, 'orders/paid_detail.html', {'order':order, 'orderitems':orderitems})

orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block content %}
    <h3>Cart</h3>
    <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Total Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ item.product }}</td>
      <td>{{ item.price }}</td>
      <td>{{ item.quantity}}</td>
      <td>{{ item.total_price}}</td>
      <td><a href="{% url 'orders:cart_remove' item.product.id %}" class="btn btn-danger">Remove</a></td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan="4">{% if cart.get_total_price is not 0 %} Total Cart Price {% else %} your Cart is empty {% endif %}</td>
      <td colspan="2">{{cart.get_total_price}}</td> 
    </tr>
  </tbody>
</table>
<br\>
<a class="{% if cart.get_total_price is 0 %} disabled {% endif %} btn btn-primary " href="{% url 'orders:order_create' %}">Checkout</a>
<br><br><br\>

<a class="btn btn-danger" href="{% url 'orders:unpaid_orders' %}">unpaid orders</a>
{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}

{% block content %}
    <h3>Checkout</h3>
    <p>Total Price : {{ order.get_total_price }} </p>
    <br\><br\>

    {% if not order.discount %}
    <form action="" method="post" class="btn btn-warning">
        {% csrf_token %}
        enter your coupon here
             
        {{ form.as_p}}
        <input type="submit" value="Apply">
    </form>
    {% endif %}
    <br\><br\>
    <a class="btn btn-primary" href="{% url 'orders:order_pay' order.id %}">Pay</a>

{% endblock %}

orders/templates/orders/paid_detail.html
{% extends 'base.html' %}

{% block content %}
    <h3>piad Order number {{ order.id }}</h3>
    <br><br\>
    
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
    {% for item in orderitems %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ item.product }}</td>
      <td>{{ item.price }}</td>
      <td>{{ item.quantity}}</td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan="2">Total Order Price</td>
      <td colspan="3">{{order.get_total_price}}</td> 
    </tr>
  </tbody>
</table>

{% endblock %}

orders/templates/orders/paid_orders.html
{% extends 'base.html' %}

{% block content %}
    <h3>piad Orders</h3>
    <br><br\>
    {% for order in orders %}
        <a class="btn btn-success" href="{% url 'orders:paid_detail' order.id %}">order number {{order.id}} with price {{ order.get_total_price }} $</a>
        <br><br\>
        <br><br\>
        <br><br\>
    {% empty %}
        <b> You dont have any paid orders</b>
    {% endfor %}
{% endblock %}

orders/templates/orders/unpaid_detail.html
{% extends 'base.html' %}

{% block content %}
    <h3>Unpiad Order number {{ order.id }}</h3>
    <br><br\>
    
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
    {% for item in orderitems %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ item.product }}</td>
      <td>{{ item.price }}</td>
      <td>{{ item.quantity}}</td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan="2">Total Order Price</td>
      <td colspan="3">{{order.get_total_price}}</td> 
    </tr>
  </tbody>
</table>
<a class="btn btn-primary" href="{% url 'orders:order_detail' order.id %}">PAY order number {{order.id}} with price {{ order.get_total_price }} $</a>
        <br><br\>
        <br><br\>
        <br><br\>

{% endblock %}

orders/templates/orders/unpaid_orders.html
{% extends 'base.html' %}

{% block content %}
    <h3>Unpiad Orders</h3>
    <br><br\>
    {% for order in orders %}
        <a class="btn btn-secondary" href="{% url 'orders:unpaid_detail' order.id %}">order number {{order.id}} with price {{ order.get_total_price }} $</a>
        <a class="btn btn-danger" href="{% url 'orders:delete_unpaid' order.id %}">Delete this order $</a>
        <br><br\>
        <br><br\>
        <br><br\>
    {% empty %}
        <b> ✅ You dont have any unpaid orders</b>
    {% endfor %}
{% endblock %}