accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('update_profile/', views.UserUpdateProfileView.as_view(), name='update_profile'),
    path('change_password/', views.UserChangePasswordView.as_view(), name='change_password'),
    path('reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('otplogin/', views.UserOtpLoginView.as_view(), name='user_otplogin'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('loginverify/', views.UserLoginVerifyCodeView.as_view(), name='login_verify_code'),
    path('upload_profile/', views.UploadProfileImageView.as_view(), name='upload_profile'),
    path('change_sms_form/', views.ChangeSmsFormView.as_view(), name='change_sms_form'),
    path('api_register/', views.ApiRegisterView.as_view(), name='api_register'),
    path('api_login/', views.ApiLoginView.as_view(), name='api_login'),
    path('api_logout/', views.ApiLogoutView.as_view(), name='api_logout'),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj/<str:key>', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
    path('upload/', views.UploadImageView.as_view(), name='upload'),
    
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('bucket_pics/',views.BucketPicsView.as_view(), name='bucket_pics'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('favorite/<slug:slug>/', views.FavoriteView.as_view(), name='product_fav'),
    path('favorites_list/', views.MyFavoritesListView.as_view(), name='my_fav_pr'),
    path('api/', views.ApiView.as_view(), name='api'),
    path('api_request/', views.PersonApiRequestView.as_view(), name='api_req'),
    path('api_request_user/', views.UserApiRequestView.as_view(), name='api_req_user'),
    path('api_question/', views.QuestionApiRequestView.as_view(), name='api_question'),    
    path('api_question/create/', views.QuestionApiCreateView.as_view(), name='api_q_create'),
    path('api_question/Update/<int:pk>/', views.QuestionApiUpdateView.as_view(), name='api_q_update'),
    path('api_question/Delete/<int:pk>/', views.QuestionApiDeleteView.as_view(), name='api_q_delete'),
    path('ai_page/', views.AiPageView.as_view(), name='ai_page'),
    
]
# bucket should be higher than product_detail and delete
# path('upload_obj/', views.UploadBucketObject.as_view(), name='upload_obj_bucket'),

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('unpaid/', views.UnpaidOrderView.as_view(), name='unpaid_orders'),
    path('paid/', views.paidOrderView.as_view(), name='paid_orders'),
    path('unpaid_detail/<int:order_id>/', views.UnpaidDetailView.as_view(), name='unpaid_detail'),
    path('paid_detail/<int:order_id>/', views.PaidDetailView.as_view(), name='paid_detail'),
    path('delete_unpaid/<int:order_id>/', views.DeleteUnpaidOrderView.as_view(), name='delete_unpaid'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# dont forget to delete "+ static(settings..." in production mode

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager
from django.core.validators import RegexValidator

only_digits = RegexValidator(regex=r'^\d+$', message='please enter just numbers')
ten_digits = RegexValidator(regex=r'^\d{10}$', message='please enter exactly 10 digits number')

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    full_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    address = models.TextField(max_length=1000, null=True, blank=True, default="")
    postal_code = models.CharField(max_length=10, null=True, blank=True, default="", validators=[ten_digits])
    national_id = models.CharField(max_length=10, null=True, blank=True, default="", validators=[ten_digits])
    birthday = models.DateField(null=True, blank=True, default="1990-01-01")
    image_url = models.URLField(max_length=500, blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number' # this fields must have unique=True .
    REQUIRED_FIELDS = ['email', 'full_name'] # only works for createsuperuser. password and USERNAME_FIELD will be asked without being inserted here.

    def __str__(self):
        return self.email
    
    @property
    def is_staff(self):
        return self.is_admin
    

class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11, unique=True)
    code = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.phone_number} - {self.code} - {self.created}'

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profile')
    age = models.PositiveSmallIntegerField(default=20)
    bio = models.TextField(null=True, blank=True)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import UserCreationForm, VerifyCodeForm, UserLoginForm, UserOtpLoginForm, UserChagePasswordForm
from .forms import UserUpdateProfileForm, ProfileImageUploadForm, ChangeSmsForm, ApiRegisterForm, ApiLoginForm
import random, pytz, os, requests
from utils import send_otp_code, get_api_user, generate_token
from .models import OtpCode, User
from django.contrib import messages
from datetime import datetime, timedelta
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from .tasks import send_otp_code_task, bucket
from shop import settings
from django.contrib.auth import views as auth_views, update_session_auth_hash
from django.urls import reverse_lazy
from bucket import bucket
from . import tasks
from django.views.generic import TemplateView, RedirectView, ListView

class UserRegisterView(ListView):
    form_class = UserCreationForm
    template_name = 'accounts/register.html'
    
    def get(self, request):
        form = self.form_class # no prantesis is needed
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            random_code = random.randint(1000, 9999)
            send_otp_code(form.cleaned_data['phone_number'], random_code)
            OtpCode.objects.create(phone_number=form.cleaned_data['phone_number'], code=random_code)
            request.session['user_registration_info'] = {
                'phone_number' : form.cleaned_data['phone_number'],
                'email' : form.cleaned_data['email'],
                'full_name' : form.cleaned_data['full_name'],
                'password' : form.cleaned_data['password1'], 
            }
            messages.success(request, 'we sent you a code.', 'success')
            return redirect('accounts:verify_code')
        return render(request, self.template_name, {'form':form})
    

class UserRegisterVerifyCodeView(View):
    form_class = VerifyCodeForm

    def get(self, request):
        form = self.form_class
        return render(request, 'accounts/verify.html', {'form':form})


    def post(self, request):
        expiration_seconds = 120
        user_session = request.session['user_registration_info']
        code_instance = OtpCode.objects.get(phone_number = user_session['phone_number'])
        form = self.form_class(request.POST)
        expire_check = datetime.now(pytz.timezone('UTC')) - code_instance.created
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code and expire_check < timedelta(seconds=expiration_seconds) :
                User.objects.create_user(user_session['phone_number'], 
                                         user_session['email'], 
                                         user_session['full_name'], 
                                         user_session['password'])
                code_instance.delete()
                messages.success(request, 'you registered successfully', 'success')
            elif cd['code'] == code_instance.code and expire_check > timedelta(seconds=expiration_seconds) :
                messages.error(request, 'this code is expired, please try again.', 'danger')
                code_instance.delete()
                return redirect('accounts:verify_code')
            else:
                messages.error(request, 'this code is wrong.', 'danger')
                return redirect('accounts:verify_code')
        return redirect('home:home')
    

class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, phone_number=cd['phone_number'], password=cd['password'])
            if user is not None:
                login(request,user)
                messages.success(request,f'welcome {user.full_name}, you just logged in successfully', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            messages.error(request, 'Username or Password is not correct!', 'warning')
        return render(request, self.template_name, {'form':form})
    

class UserLogoutView(LoginRequiredMixin, RedirectView):
    pattern_name = 'home:home'
    def get_redirect_url(self, *args, **kwargs):
        logout(self.request) # we can access request by self.request
        messages.success(self.request, 'you logged out successfully','success')
        return super().get_redirect_url(*args, **kwargs)
    """def get(self, request): 
        logout(request)
        messages.success(request, 'you logged out successfully','success')
        return redirect('home:home')"""
    
class UserOtpLoginView(View):
    form_class = UserOtpLoginForm
    template_name = 'accounts/otplogin.html'
    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            random_code = random.randint(1000, 9999)
            if settings.CELERY_IS_ACTIVE:
                send_otp_code_task.delay(form.cleaned_data['phone_number'], random_code, request)
            else:
                send_otp_code(form.cleaned_data['phone_number'], random_code, request)
                print("settings.CELERY_IS_ACTIVE is False")
            OtpCode.objects.create(phone_number=form.cleaned_data['phone_number'], code=random_code)
            request.session['user_otplogin_info'] = {'phone_number' : form.cleaned_data['phone_number']}
            messages.success(request, 'we sent you a code.', 'success')
            return redirect('accounts:login_verify_code')
        return render(request, self.template_name, {'form':form})


class UserLoginVerifyCodeView(View):
    form_class = VerifyCodeForm
    template_name = 'accounts/otplogin.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        expiration_seconds = 120
        form = self.form_class(request.POST)
        user_session = request.session['user_otplogin_info']
        if form.is_valid():
            phone = user_session['phone_number']
            code_instance = OtpCode.objects.get(phone_number = phone)
            expire_check = datetime.now(pytz.timezone('UTC')) - code_instance.created
            user = User.objects.filter(phone_number=phone).first() # this is important to get None instead of DoesNotExsitsError,
            # also no leakage! or we can use try-except block.
            if user is not None and code_instance.code == form.cleaned_data['code'] and expire_check < timedelta(seconds=expiration_seconds):
                login(request,user)
                code_instance.delete()
                messages.success(request,f'welcome {user.email}. you logged in successfully', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            elif user is not None and expire_check > timedelta(seconds=expiration_seconds) :
                messages.error(request, 'this code is expired, please try again.', 'danger')
                code_instance.delete()
                return redirect('accounts:user_otplogin')
            messages.error(request, 'Username or OTP-Code is not correct!', 'warning')
            return redirect('accounts:login_verify_code')
        return render(request, self.template_name, {'form':form})

class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'
    
class UserUpdateProfileView(LoginRequiredMixin, View):
    form_class = UserUpdateProfileForm
    template_name = 'accounts/update_profile.html'
    def get(self, request):
        form = self.form_class(instance=request.user)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            request.user.full_name, request.user.address, request.user.postal_code = cd['full_name'], cd['address'], cd['postal_code']
            request.user.national_id, request.user.birthday = cd['national_id'], cd['birthday']
            request.user.save()
            messages.success(request, 'Your profile has been updated', 'success')
            return redirect('accounts:profile')
        return render(request, self.template_name, {'form':form})
    
class UserChangePasswordView(LoginRequiredMixin, View):
    template_name = 'accounts/change_password.html'
    def get(self, requset):
        form = UserChagePasswordForm()
        return render(requset, self.template_name, {'form':form})
    
    def post(self, request):

accounts/templates/accounts/api_login.html
{% extends 'base.html' %}

{% block content %}
    <h2>API Login Form</h2><br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
    <br>
{% endblock %}

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
     <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change Password">
    </form>
{% endblock %}

accounts/templates/accounts/changesmsform.html
{% extends 'base.html' %}

{% block content %}
    <h2>Change SMS Parameters Form</h2><br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change SMS Parameters">
    </form>
    <br>
    <br>
    <b></b>
    
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h2>Login Form</h2><br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
    <br><br>
    <b>Problem logging in? use </b>
    <a href="{% url 'accounts:user_otplogin' %}" class="btn btn-info">OTP Login</a>
    <br><br>
    <b> or </b>
    <a href="{% url 'accounts:password_reset' %}" class="btn btn-info">Reset Password With Email</a>
{% endblock %}

accounts/templates/accounts/otplogin.html
{% extends 'base.html' %}

{% block content %}
    <h2>OTP Login Form</h2><br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
     <p> your password changed successfully.</p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    {% if validlink %}
     <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change">
    </form>
    {% else %}
        <p>link was not valid, please try again. </p>
    {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
     <p> We just sent you an email. please check it out.</p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
hi Someone asked for password reset for email {{ email }}.
Please follow the link below: 
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
     <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'accounts:update_profile' %}" class="btn btn-info">Update Profile</a>
    <a href="{% url 'accounts:change_password' %}" class="btn btn-warning">Change Password</a>
    <a href="{% url 'orders:unpaid_orders' %}" class="btn btn-danger">Unpaid Orders</a>
    <a href="{% url 'orders:paid_orders' %}" class="btn btn-success">Paid Orders</a>
    <a href="{% url 'home:my_fav_pr' %}" class="btn btn-primary">My Favorite Products</a>
    <a href="{% url 'accounts:upload_profile' %}" class="btn btn-secondary">Upload Profile Image</a>
    <br><br><br>
    <h2>Profile</h2><br>
    {% if request.user.image_url %}
    <img src="{{ request.user.image_url }}" class="card-img-top" style="max-width: 200px;">
    {% endif %}
    <br><br>
    <b>Name: {{ request.user.full_name }}</b><br><br>
    <b>Email: {{ request.user.email }}</b><br><br>
    <b>Phone Number: {{ request.user.phone_number }}</b><br><br>
{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends 'base.html' %}

{% block content %}
<h2>Update Profile</h2><br>

<form>
  <div class="mb-6">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" value="{{request.user.email}}" readonly data-bs-toggle="tooltip"
           title="You can not change this field">
    </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Phone Number</label>
    <input class="disabled form-control" value="{{request.user.phone_number}}" readonly data-bs-toggle="tooltip"
           title="You can not change this field">
  </div>
</form>

    <b>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-primary">
    </form>
    </b>
{% endblock %}

accounts/templates/accounts/upload_profile.html
{% extends 'base.html' %}

{% block content %}
<h4>Upload Media</h4>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Upload">
    </form>
{% endblock %}

accounts/templates/accounts/verify.html
{% extends 'base.html' %}

{% block content %}
    <h2>OTP-CODE FORM</h2><br>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}