accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('update_profile/', views.UserUpdateProfileView.as_view(), name='update_profile'),
    path('change_password/', views.UserChangePasswordView.as_view(), name='change_password'),
    path('reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('otplogin/', views.UserOtpLoginView.as_view(), name='user_otplogin'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('loginverify/', views.UserLoginVerifyCodeView.as_view(), name='login_verify_code'),
    path('upload_profile/', views.UploadProfileImageView.as_view(), name='upload_profile'),
    path('change_sms_form/', views.ChangeSmsFormView.as_view(), name='change_sms_form'),
    path('api_register/', views.ApiRegisterView.as_view(), name='api_register'),
    path('api_login/', views.ApiLoginView.as_view(), name='api_login'),
    path('api_logout/', views.ApiLogoutView.as_view(), name='api_logout'),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj/<str:key>', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
    path('upload/', views.UploadImageView.as_view(), name='upload'),
    
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('bucket_pics/',views.BucketPicsView.as_view(), name='bucket_pics'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('favorite/<slug:slug>/', views.FavoriteView.as_view(), name='product_fav'),
    path('favorites_list/', views.MyFavoritesListView.as_view(), name='my_fav_pr'),
    path('api/', views.ApiView.as_view(), name='api'),
    path('api_request/', views.PersonApiRequestView.as_view(), name='api_req'),
    path('api_request_user/', views.UserApiRequestView.as_view(), name='api_req_user'),
    path('api_question/', views.QuestionApiRequestView.as_view(), name='api_question'),    
    path('api_question/create/', views.QuestionApiCreateView.as_view(), name='api_q_create'),
    path('api_question/Update/<int:pk>/', views.QuestionApiUpdateView.as_view(), name='api_q_update'),
    path('api_question/Delete/<int:pk>/', views.QuestionApiDeleteView.as_view(), name='api_q_delete'),
    path('ai_page/', views.AiPageView.as_view(), name='ai_page'),
    
]
# bucket should be higher than product_detail and delete
# path('upload_obj/', views.UploadBucketObject.as_view(), name='upload_obj_bucket'),

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('unpaid/', views.UnpaidOrderView.as_view(), name='unpaid_orders'),
    path('paid/', views.paidOrderView.as_view(), name='paid_orders'),
    path('unpaid_detail/<int:order_id>/', views.UnpaidDetailView.as_view(), name='unpaid_detail'),
    path('paid_detail/<int:order_id>/', views.PaidDetailView.as_view(), name='paid_detail'),
    path('delete_unpaid/<int:order_id>/', views.DeleteUnpaidOrderView.as_view(), name='delete_unpaid'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# dont forget to delete "+ static(settings..." in production mode

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <ul class="navbar-nav me-auto mb-2 mb-lg-1">
        <li class="nav-item">
          <a class="nav-link active me-2" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a type="button" class="btn btn-primary position-relative me-2" href="{% url 'orders:cart' %}">
            Cart
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
              {{ cart_cp|length }}
              <span class="visually-hidden">unread messages</span>
            </span>
          </a>
        </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-1">
          {% if request.session.api_username %}
          <li class="nav-item">
            <a class="btn btn-warning ms-2" href="#">API user: {{ request.session.api_username }} (id: {{ request.session.api_id }})</a>
          </li>
          {% endif %}
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="btn btn-secondary ms-2" href="{% url 'accounts:profile' %}">{{ request.user.full_name }}</a>
          </li>
          {% if request.user.is_superuser %}
          <li class="nav-item">
            <a class="btn btn-info ms-2" href="{% url 'home:api' %}">API</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-danger ms-2" href="{% url 'home:bucket' %}">Bucket</a>
          </li>
          {% endif %}
          
          <li class="nav-item">
            <a class="nav-link active ms-2" href="{% url 'accounts:user_logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item"></li>
          <a class="nav-link active ms-2" href="{% url 'accounts:user_register' %}">Register</a>
          </li>
          <li class="nav-item"></li>
            <a class="nav-link active ms-2" href="{% url 'accounts:user_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
    </div>
</nav>